import 'reflect-metadata';
import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';
import { GraphQLSchemaHost } from '@nestjs/graphql';
import { lexicographicSortSchema, printSchema } from 'graphql';
import { writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { config } from 'dotenv';
import { INestApplicationContext } from '@nestjs/common';

async function main() {
  const path = resolve(__dirname, process.env.ENV_FILE ?? '../.env');
  console.log(path);
  config({ path });
  let app: INestApplicationContext = null as unknown as INestApplicationContext;
  try {
    app = await NestFactory.createApplicationContext(AppModule);
    const { schema } = app.get(GraphQLSchemaHost);
    const sortedSchema = lexicographicSortSchema(schema);
    const sdl = printSchema(sortedSchema);
    const outPath = join(process.cwd(), 'generated.graphql');
    writeFileSync(
      outPath,
      `# This file is automatically generated by running pnpm gql:all. Do not edit manually.

${sdl}`,
      'utf8',
    );
    console.log(`Schema written to ${outPath}`);
  } catch (e) {
    console.log('Error during schema generation', e);
    throw e;
  } finally {
    await app.close();
  }
}

main().catch((e) => {
  console.log(e);
  process.exit(1);
});
