import type { CodegenConfig } from '@graphql-codegen/cli';

// We generate frontend types/hooks from local SDL emitted by backend.
// This avoids requiring a running backend server during codegen.

const config: CodegenConfig = {
  // Use local emitted schema (generated by backend script) to avoid needing a running server
  schema: '../backend/generated.graphql',
  documents: 'src/graphql/**/*.{ts,tsx}',
  generates: {
    'src/graphql/__generated__/index.ts': {
      plugins: [
        'typescript',
        'typescript-operations',
        'typescript-react-apollo',
      ],
      config: {
        withHooks: true,
        withHOC: false,
        withComponent: false,
        dedupeOperationSuffix: true,
        avoidOptionals: true,
        enumsAsTypes: true,
        defaultScalarType: 'unknown',
        scalars: {
          DateTime: 'string',
          Decimal: {
            input: 'import("@rebalancing-helper/common").DecimalInput',
            output: 'import("@rebalancing-helper/common").Decimal',
          },
        },
      },
    },
  },
  hooks: { afterAllFileWrite: ['prettier --write'] },
};

export default config;
