name: PR Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    env:
      CI: true
      DATABASE_URL: file:${{ github.workspace }}/packages/backend/prisma/dev.db
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'

      - name: Enable Corepack
        run: corepack enable

      - name: Restore Turborepo cache
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ hashFiles('turbo.json', 'yarn.lock') }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-${{ hashFiles('turbo.json', 'yarn.lock') }}-
            ${{ runner.os }}-turbo-

      - name: Install dependencies
        run: yarn install --immutable

      - name: Generate Prisma Client
        run: yarn workspace backend prisma generate

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test
